package com.example.logisticshub.db

import android.content.Context
import com.squareup.sqldelight.android.AndroidSqliteDriver

class AndroidDatabaseDriverFactory(private val context: Context) : DatabaseDriverFactory {
    override fun createDriver(): Any {
        // LogisticsDb is generated by SQLDelight based on shared/sqldelight/pickups.sq
        return AndroidSqliteDriver(LogisticsDb.Schema, context, "logistics.db")
    }
}
